### ISSUE TITLE
执行器运行 datax 获取 hive 元数据异常

### ISSUE THREAD

**Issue by peniridis** [WeBankFinTech/Exchangis#10]
### 日志
```
2020-05-26 12:03:18.235 [job-1476524239652786176] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All task WaitWriterTime 0.000s |  All task WaitReaderTime 0.000s | Percentage 0.00%
2020-05-26 12:03:18.345 [job-1476524239652786176] ERROR Engine - 

该任务最可能的错误原因是:

com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:
[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - 
java.lang.NoSuchMethodError: 
org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(Lorg/apache/hadoop/con
f/Configuration;Lorg/apache/hadoop/hive/metastore/HiveMetaHookLoader;Ljava/util/concurrent
/ConcurrentHashMap;Ljava/lang/String;Z)Lorg/apache/hadoop/hive/metastore/IMetaStoreClien;
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:4299)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:4367)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:4347)
	at org.apache.hadoop.hive.ql.metadata.Hive.getAllFunctions(Hive.java:4603)
	at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:291)
	at org.apache.hadoop.hive.ql.metadata.Hive.registerAllFunctionsOnce(Hive.java:274)
	at org.apache.hadoop.hive.ql.metadata.Hive.<init>(Hive.java:435)
	at org.apache.hadoop.hive.ql.metadata.Hive.create(Hive.java:375)
	at org.apache.hadoop.hive.ql.metadata.Hive.getInternal(Hive.java:355)
	at org.apache.hadoop.hive.ql.metadata.Hive.get(Hive.java:331)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriterUtil.lambda$getHiveConnByUris$5(HdfsWriterUtil.java:935)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriterUtil.getHiveConnByUris(HdfsWriterUtil.java:934)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriterUtil.updateConfigByHiveMeta(HdfsWriterUtil.java:218)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Job.prepare(HdfsWriter.java:187)
	at com.alibaba.datax.core.job.JobContainer.lambda$prepareJobWriter$3(JobContainer.java:846)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:841)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:367)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:132)
	at com.alibaba.datax.core.Engine.start(Engine.java:98)
	at com.alibaba.datax.core.Engine.entry(Engine.java:177)
	at com.alibaba.datax.core.Engine.main(Engine.java:242)
```
求助！
是缺少 hive-metastore 这个包吗？

**Comment by Davidhua1996** [comment]
What is your version of Hive client? You can check if “hive-metastore-{version}.jar" exists in directory: modules/exchangis-executor/engine/datax/plugin/writer/hdfswriter/libs

**Comment by peniridis** [comment]
我变更版本 忘记 clean install 嘿嘿嘿，还是不瞎搞了
