### ISSUE TITLE
[Bug] 任务执行失败

### ISSUE THREAD

**Issue by xixinpeng436** [WeBankFinTech/Exchangis#391]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar issues.

### Exchangis Component

exchangis-job-server

### What happened + What you expected to happen

[测试同步数据到hive], expect subJobs: [1]
2023-01-13 11:21:15.150 [ERROR] [Multi-Tenancy-Group-hadoop-Executor-2   ] c.w.w.e.j.s.e.g.DefaultTaskGenerator (69) [lambda$error$5] - Error occurred in generating com.webank.wedatasphere.exchangis.job.server.exception.ExchangisTaskGenerateException: errCode: 31997 ,desc: Error in generating launchable tasks ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:110) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:63) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:24) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.tasks.GenerationSchedulerTask.schedule(GenerationSchedulerTask.java:37) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.AbstractExchangisSchedulerTask$DirectExecuteRequest.directExecute(AbstractExchangisSchedulerTask.java:92) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.ExchangisSchedulerExecutorManager$DefaultDirectExecutor.execute(ExchangisSchedulerExecutorManager.java:166) ~[exchangis-job-server-1.0.0.jar:?]
	at org.apache.linkis.scheduler.queue.Job$$anonfun$3.apply(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at org.apache.linkis.scheduler.queue.Job$$anonfun$3.apply(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
	at org.apache.linkis.scheduler.queue.Job.run(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: com.webank.wedatasphere.exchangis.job.exception.ExchangisJobException: errCode: 31998 ,desc: Fail to build transformJob from input job, message: [null] ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:129) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:26) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.AbstractExchangisJobBuilder.build(AbstractExchangisJobBuilder.java:50) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.GenericExchangisJobBuilderChain.build(GenericExchangisJobBuilderChain.java:40) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:39) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:30) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:85) ~[exchangis-job-server-1.0.0.jar:?]
	... 14 more
Caused by: java.lang.NullPointerException
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.timePlaceHolderConvert(TransformExchangisJob.java:170) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.convertContentToParams(TransformExchangisJob.java:87) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.<init>(TransformExchangisJob.java:68) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.lambda$buildJob$6(GenericExchangisTransformJobBuilder.java:81) ~[exchangis-job-server-1.0.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_351]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_351]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_351]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_351]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:86) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:26) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.AbstractExchangisJobBuilder.build(AbstractExchangisJobBuilder.java:50) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.GenericExchangisJobBuilderChain.build(GenericExchangisJobBuilderChain.java:40) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:39) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:30) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:85) ~[exchangis-job-server-1.0.0.jar:?]
	... 14 more

2023-01-13 11:21:15.156 [ERROR] [Multi-Tenancy-Group-hadoop-Executor-2   ] c.w.w.e.j.s.l.DefaultRpcJobLogger$ (24) [onEvent] - [hadoop:9a8e20cc-3084-4444-9ebd-ffc495598d20] Error occurred in generating com.webank.wedatasphere.exchangis.job.server.exception.ExchangisTaskGenerateException: errCode: 31997 ,desc: Error in generating launchable tasks ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:110) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:63) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:24) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.tasks.GenerationSchedulerTask.schedule(GenerationSchedulerTask.java:37) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.AbstractExchangisSchedulerTask$DirectExecuteRequest.directExecute(AbstractExchangisSchedulerTask.java:92) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.ExchangisSchedulerExecutorManager$DefaultDirectExecutor.execute(ExchangisSchedulerExecutorManager.java:166) ~[exchangis-job-server-1.0.0.jar:?]
	at org.apache.linkis.scheduler.queue.Job$$anonfun$3.apply(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at org.apache.linkis.scheduler.queue.Job$$anonfun$3.apply(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
	at org.apache.linkis.scheduler.queue.Job.run(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: com.webank.wedatasphere.exchangis.job.exception.ExchangisJobException: errCode: 31998 ,desc: Fail to build transformJob from input job, message: [null] ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:129) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:26) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.AbstractExchangisJobBuilder.build(AbstractExchangisJobBuilder.java:50) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.GenericExchangisJobBuilderChain.build(GenericExchangisJobBuilderChain.java:40) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:39) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:30) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:85) ~[exchangis-job-server-1.0.0.jar:?]
	... 14 more
Caused by: java.lang.NullPointerException
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.timePlaceHolderConvert(TransformExchangisJob.java:170) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.convertContentToParams(TransformExchangisJob.java:87) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.<init>(TransformExchangisJob.java:68) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.lambda$buildJob$6(GenericExchangisTransformJobBuilder.java:81) ~[exchangis-job-server-1.0.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_351]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_351]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_351]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_351]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:86) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:26) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.AbstractExchangisJobBuilder.build(AbstractExchangisJobBuilder.java:50) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.GenericExchangisJobBuilderChain.build(GenericExchangisJobBuilderChain.java:40) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:39) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:30) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:85) ~[exchangis-job-server-1.0.0.jar:?]
	... 14 more

2023-01-13 11:21:15.167 [INFO ] [Multi-Tenancy-Group-hadoop-Executor-2   ] c.w.w.e.j.s.e.s.t.GenerationSchedulerTask (41) [info] - Scheduler-GenerationTask-9a8e20cc-3084-4444-9ebd-ffc495598d20 change status Running => Failed.
2023-01-13 11:21:15.168 [ERROR] [Multi-Tenancy-Group-hadoop-Executor-2   ] c.w.w.e.j.s.e.s.AbstractExchangisSchedulerTask (108) [transitionCompleted] - Schedule Error: Exception occurred in scheduling, task will fail or retry on the next time, message: [errCode: 31994 ,desc: Exception in generating launchable tasks: [ name: 测试同步数据到hive, job_execution_id: 9a8e20cc-3084-4444-9ebd-ffc495598d20] ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server] com.webank.wedatasphere.exchangis.job.server.exception.ExchangisSchedulerException: errCode: 31994 ,desc: Exception in generating launchable tasks: [ name: 测试同步数据到hive, job_execution_id: 9a8e20cc-3084-4444-9ebd-ffc495598d20] ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.tasks.GenerationSchedulerTask.schedule(GenerationSchedulerTask.java:46) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.AbstractExchangisSchedulerTask$DirectExecuteRequest.directExecute(AbstractExchangisSchedulerTask.java:92) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.ExchangisSchedulerExecutorManager$DefaultDirectExecutor.execute(ExchangisSchedulerExecutorManager.java:166) ~[exchangis-job-server-1.0.0.jar:?]
	at org.apache.linkis.scheduler.queue.Job$$anonfun$3.apply(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at org.apache.linkis.scheduler.queue.Job$$anonfun$3.apply(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
	at org.apache.linkis.scheduler.queue.Job.run(Job.scala:266) ~[linkis-scheduler-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: com.webank.wedatasphere.exchangis.job.server.exception.ExchangisTaskGenerateException: errCode: 31997 ,desc: Error in generating launchable tasks ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:110) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:63) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:24) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.tasks.GenerationSchedulerTask.schedule(GenerationSchedulerTask.java:37) ~[exchangis-job-server-1.0.0.jar:?]
	... 11 more
Caused by: com.webank.wedatasphere.exchangis.job.exception.ExchangisJobException: errCode: 31998 ,desc: Fail to build transformJob from input job, message: [null] ,ip: localhost ,port: 19999 ,serviceKind: exchangis-server
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:129) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:26) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.AbstractExchangisJobBuilder.build(AbstractExchangisJobBuilder.java:50) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.GenericExchangisJobBuilderChain.build(GenericExchangisJobBuilderChain.java:40) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:39) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:30) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:85) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:63) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:24) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.tasks.GenerationSchedulerTask.schedule(GenerationSchedulerTask.java:37) ~[exchangis-job-server-1.0.0.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.timePlaceHolderConvert(TransformExchangisJob.java:170) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.convertContentToParams(TransformExchangisJob.java:87) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.TransformExchangisJob$SubExchangisJobAdapter.<init>(TransformExchangisJob.java:68) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.lambda$buildJob$6(GenericExchangisTransformJobBuilder.java:81) ~[exchangis-job-server-1.0.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_351]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_351]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_351]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_351]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_351]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:86) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.builder.transform.GenericExchangisTransformJobBuilder.buildJob(GenericExchangisTransformJobBuilder.java:26) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.AbstractExchangisJobBuilder.build(AbstractExchangisJobBuilder.java:50) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.api.GenericExchangisJobBuilderChain.build(GenericExchangisJobBuilderChain.java:40) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:39) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.builder.manager.DefaultExchangisJobBuilderManager.doBuild(DefaultExchangisJobBuilderManager.java:30) ~[exchangis-job-builder-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.DefaultTaskGenerator.execute(DefaultTaskGenerator.java:85) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:63) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.generator.AbstractTaskGenerator.generate(AbstractTaskGenerator.java:24) ~[exchangis-job-server-1.0.0.jar:?]
	at com.webank.wedatasphere.exchangis.job.server.execution.scheduler.tasks.GenerationSchedulerTask.schedule(GenerationSchedulerTask.java:37) ~[exchangis-job-server-1.0.0.jar:?]
	... 11 more

### Relevent platform

cenos7

### Reproduction script

echo 'wu'

### Anything else

目前使用环境是dss1.1.0+linkis1.3.0 但是exchangis包是1.0.0的官方包

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Li-GL** [comment]
遇到了同样的问题，请问问题解决了吗？

**Comment by muye559** [comment]
同问，怎么解决啊？
