### ISSUE TITLE
No available candidate servers

### ISSUE THREAD

**Issue by cubemoon** [WeBankFinTech/Exchangis#52]
exchangis-service启动起来后就持续报错。
`com.webank.wedatasphere.exchangis.route.exception.NoAvailableServerException: No available candidate servers
	at com.webank.wedatasphere.exchangis.route.MachineLoadRule.choose(MachineLoadRule.java:108)
	at com.webank.wedatasphere.exchangis.route.MachineLoadRule.choose(MachineLoadRule.java:65)
	at com.netflix.loadbalancer.BaseLoadBalancer.chooseServer(BaseLoadBalancer.java:736)
	at com.netflix.loadbalancer.ZoneAwareLoadBalancer.chooseServer(ZoneAwareLoadBalancer.java:113)
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:481)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)`

**Comment by Davidhua1996** [comment]
Warn log. It means that cannot find the suitable nodes to execute your task commited
